
;===================================================
;			RAM Define
;====================================================
.EXTERN		R_2Hz 
.EXTERN		R_128Hz
.EXTERN		R_INTFlag
.EXTERN		F_2HzWakeUp
.EXTERN		Wait1_2Sec
.EXTERN		power_1
;.EXTERN		IOD_Attmap	
;.EXTERN		IOD_Dirmap	
;.EXTERN		IOD_Datmap	
;===================================================
;			Module Define
;====================================================
.extern	        V_RESET	
.extern			L_PowerOn
;====================================================

