;No GroupName
.EXTERN		T_SPCH_B
.EXTERN		T_SPCH_H
.EXTERN		T_SPCH_L
.EXTERN		T_SPCH


;No GroupName
.EXTERN		T_SONG_B
.EXTERN		T_SONG_H
.EXTERN		T_SONG_L


;No GroupName
.EXTERN		T_BMP_B
.EXTERN		T_BMP_H
.EXTERN		T_BMP_L


;No GroupName
.EXTERN		T_DATA_B
.EXTERN		T_DATA_H
.EXTERN		T_DATA_L


;------------------------------
;Speech
;------------------------------
;Speech in movie file


;------------------------------
;Melody
;------------------------------
;Melody in movie file


;------------------------------
;Image
;------------------------------
;Image in movie file


;------------------------------
;Data
;------------------------------


